raw = {
    "Health and Wellness": {
        "morning yoga routine": "🌅🧘‍♂️✨",
        "healthy meal preparation": "🥗👩‍🍳💪",
        "stress relief meditation": "😫🧘‍♀️☺️",
        "alternative herbal therapy": "🌿💆‍♂️🌱",
        "death by chocolate dessert": "💀🍫🍰",
        "thinking about a diet plan": "🤔🥗📝",
        "crying over spilled milk": "😢🥛💔",
        "winking at wellness goals": "😉💪🎯",
        "mad about missing the gym": "😡🏋️‍♂️❌",
        "weed therapy relaxation": "🌿💆‍♂️😌",
        "hug yourself self-care": "🤗💕🧘",
        "blue mood therapy": "💙😢👩‍⚕️",
    },
    "Education and Learning": {
        "graduation celebration": "🎓🎉📚",
        "online learning platform": "💻📖🎓",
        "exploring art history": "🖼️📚🎨",
        "science laboratory experiments": "🔬🧪🧠",
        "nerd for history": "🤓📚🏛️",
        "celebrating academic achievements": "🎉🎓💯",
        "clapping for graduation": "👏🎓🥳",
        "thinking about philosophical questions": "🤔💭🌌",
        "thinking about math problems": "🤔➕🧮",
        "flushed with exam stress": "😳📝⏰",
        "face palm at a mistake": "🤦‍♂️❌💡",
        "black heart for gothic literature": "🖤📚🦇",
    },
    "Travel and Adventure": {
        "tropical island getaway": "🏝️✈️🍹",
        "cross-country road trip": "🚗🗺️🛣️",
        "exploring local culture": "🌐🎭🏺",
        "sustainable eco-tourism": "🌍🌱🏕️",
        "moonlit beach night": "🌙🏖️💏",
        "sunglasses ready for vacation": "😎✈️🌴",
        "praying for travel safety": "🙏✈️🌍",
        "waving goodbye to home": "👋🏡✈️",
        "celebrate world tour": "🎉🌍✈️",
        "wave at the tropical paradise": "🌊🏝️😎",
        "sun adventures on the beach": "🌞🏖️🏄‍♀️",
        "cowboy adventure in the wild west": "🤠🌵🐎",
    },
    "Family and Life Stages": {
        "newborn baby joy": "👶🎉💕",
        "wedding day bliss": "💑💍🎊",
        "teenager's first car": "🚗👦🔑",
        "caring for elderly parents": "👴💕👩‍⚕️",
        "kiss for a newborn baby": "💋👶💕",
        "angelic child's behavior": "👼🧒✨",
        "surprised by pregnancy news": "😲🤰🎉",
        "family Christmas celebration": "🎄👨‍👩‍👧‍👦🎁",
        "kiss under the moon": "💋🌕💑",
        "cursed teenage phase": "🧟‍♂️👦🚫",
        "prayer for family health": "🙏👨‍👩‍👧‍👦💊",
        "angelic baby smile": "👼👶😊",
        "Boomer Nostalgia": "📺🎶🕺",
        "boomer Technology Adaptation": "💾👴📱",
        "boomer's Favorite Vinyl Records": "👴🎵💿",
        "boomer Parenting Advice": "👴🧒💬",
        "boomer's Classic Car Collection": "👴🚗✨",
        "boomer's Retirement Party": "👴🎉🏖️",
        "boomer's Love for Gardening": "👴🌻🌳",
        "boomer Watching Old Movies": "👴🎥🍿",
        "boomer's Wisdom Sharing": "👴💭🧠",
        "boomer and Millennial Connection": "👴❤️🧑",
    },
    "Business and Entrepreneurship": {
        "launching a startup": "🚀💼📈",
        "branding and logo design": "✏️🎨🏢",
        "investing in the stock market": "💲📈📊",
        "business networking event": "🤝💼🏢",
        "thinking of a business idea": "🤔💼🚀",
        "high five for teamwork": "🙏🤝🏢",
        "devil's advocate in negotiations": "😈💬💼",
        "clapping for a successful deal": "👏🤝💲",
        "100% business growth": "💼💯📈",
        "blue brainstorming session": "💙🧠🌩️",
        "sunglasses for a cool entrepreneur": "😎💼🚀",
        "celebrate a company's anniversary": "🎉🏢🍰",
    },
    "Science and Discovery": {
        "groundbreaking research": "🔬💡📘",
        "protecting the environment": "🌍🛡️🌿",
        "space telescope exploration": "🪐🔭🌌",
        "innovative medical treatment": "💊🏥💡",
        "shocked by a scientific discovery": "😲🔬💡",
        "celebrate a technological breakthrough": "🎉💻🚀",
        "thinking of innovative solutions": "🤔💡🌍",
        "praying for a medical miracle": "🙏💊🏥",
        "think like a scientist": "🤔🧪🔍",
        "laugh at a funny experiment": "😆🔬💥",
        "prayer for scientific breakthrough": "🙏🧠📈",
        "surprised by a new invention": "😲🤖✨",
    },
    "Hobbies and Recreation": {
        "playing a musical instrument": "🎹🎼🎵",
        "painting a masterpiece": "🎨🖼️✨",
        "mountain biking adventure": "🚵‍♀️⛰️🌲",
        "gardening and landscaping": "🌻🏡🌳",
        "peach pie baking": "🍑🥧😋",
        "wink at a game victory": "😉🎮🏆",
        "emo music jam session": "🎸🖤🎶",
        "cat and book cozy evening": "😺📖☕",
    },
    "Culture and Society": {
        "women's rights movement": "♀️✊💪",
        "traditional dance festival": "💃🥁🎉",
        "high fashion runway": "👗👠📸",
        "binge-watching favorite series": "📺🍿😃",
        "laughing at a funny movie": "😆🎬🍿",
        "cat cuddling time": "😺💕🛋️",
        "sparkle in the artist's eye": "✨🎨🖼️",
        "sobbing at a sad novel": "😭📖❤️",
        "clowning around at a party": "🤡🎉🎈",
        "sheesh expression in youth culture": "😅✌️",
        "celebrating cultural diversity": "🎉🌍🤝",
        "yellow heart for friendship": "💛👫✨",
        "devil's advocate in politics": "😈💬🗳️",
        "clap for a cultural performance": "👏💃🎭",
        "funny social media meme": "😂📱🔥",
        "heart hands for community love": "🤲❤️🏘️",
    },
    "Nature and Environment": {
        "bird watching in the forest": "🦉🌲🔭",
        "sunset beach walk": "🌅🏖️👣",
        "snow-capped mountain hike": "🏔️🥾❄️",
        "urban rooftop garden": "🏙️🌷🍅",
        "sunrise meditation": "🌞🧘‍♀️🌅",
        "blushing at a beautiful flower": "😊🌸💖",
        "cowboy on a nature trail": "🤠🐴🌲",
        "surprised by a wild animal": "😲🦌🌳",
        "praying for rain in drought": "🙏💧🌾",
        "sun-loving plants": "🌞🌻🌿",
        "sad face for deforestation": "☹️🌳❌",
        "surprised by nature's beauty": "😲🏞️💖",
    },
    "Spirituality and Philosophy": {
        "praying in a temple": "🙏⛩️🕊️",
        "mindfulness meditation practice": "🧘‍♀️☮️🕉️",
        "debating ethical issues": "💭⚖️🗣️",
        "exploring existential thoughts": "🌌🤔💭",
        "prayer for inner peace": "🙏☮️💖",
        "angel guidance in life": "👼💫🌈",
        "thinking about life's meaning": "🤔🌌🌀",
        "fingers crossed for good luck": "🤞🍀✨",
        "sheesh moment in meditation": "😅🧘‍♂️",
        "chef's kiss for life's beauty": "👨‍🍳💋🌺",
        "winking at existential questions": "😉❓🌌",
        "angel guidance in dreams": "👼💤🌈",
    },
    "Emotions and Relationships": {
        "musical soulmates": "🎵💑🎶",
        "writing love letters": "✍️❤️💌",
        "having hearts in your eyes": "😍❤️👀",
        "building bridges of friendship": "👬🌉💕",
        "cooking up a love potion": "🍲💘🔮",
    },
    "Sexuality and Flirtation": {
        "suggestive eggplant": "🍆😉",
        "flirtatious peach": "🍑😏",
        "taco metaphor": "🌮😋",
        "playful invitation": "👅🍑💦",
    },
    "Adventure and Exploration": {
        "stepping into a new world": "🚪🌈🌍",
        "time travel adventure": "⏰🌀🕰️",
        "astronaut's space exploration": "👩‍🚀🚀🪐",
        "exploration of ancient ruins": "🏺🗺️🏰",
    },
    "Wellness and Leisure": {
        "meditation by the sea": "🧘‍♀️🌊☮️",
        "sunset yoga retreat": "🌅🧘‍♂️🌿",
        "savoring gourmet cuisine": "👨‍🍳🍽️😋",
        "glamping under the stars": "⛺✨🥂",
        "lost in a good book": "📚😲🌎",
    },
    "Career and Personal Development": {
        "climbing the corporate ladder": "👨‍💼🔝🏢",
        "financial independence success": "💵🔓🥳",
        "chasing your dreams": "💭🏃‍♂️🌟",
    },
    "Art, Creativity, and Expression": {
        "healing through art therapy": "🎨💔❤️",
        "poetic muse inspiration": "✒️🧚‍♀️💫",
        "festival of colors celebration": "🎉🌈🎨",
    },
    "Technology and Innovation": {
        "virtual reality gaming": "🎮🕶️🌐",
        "cybersecurity shield": "🖥️🔒🛡️",
        "robotic innovation in healthcare": "🤖💊🏥",
        "robotic automation revolution": "🤖🏭💼",
        "innovative 3D printing": "🖨️✨🏠",
        "social media influencer success": "📱💫👑",
        "AI-powered future": "🧠💻🚀",
        "green energy innovation": "🌿💡🌍",
        "futuristic smart home": "🏠💻🌟",
        "digital art creation": "🎨💻✨",
        "online shopping spree": "📱🛒💸",
    },
    "Fantasy and Entertainment": {
        "surviving the zombie apocalypse": "🧟‍♂️🔫🏃‍♀️",
        "detective solving a mystery": "🕵️‍♂️🔍❓",
    },
    "Social Justice and Sustainability": {
        "fighting for justice": "⚖️✊💪",
        "sustainable living and recycling": "♻️🌍💚",
    },
    "Transitions and Milestones": {
        "sailing into retirement": "⛵🌅🎉",
        "urban gardening oasis": "🏙️🌱🏡",
    },
    "Sports and Fitness": {
        "winning a marathon": "🏃‍♂️🥇🎉",
        "boxing training session": "🥊💪🏋️‍♂️",
        "snowboarding on a mountain": "🏂🏔️❄️",
        "yoga flexibility challenge": "🧘‍♀️💪🌺",
        "surfing the ocean waves": "🏄‍♀️🌊🤙",
        "cheering for your favorite team": "📣⚽💙",
        "achieving fitness goals": "💪🎯✅",
        "playing golf with friends": "🏌️‍♂️⛳👬",
        "basketball slam dunk": "🏀💥🏆",
        "dancing for joy": "💃🎶😄",
        "ice skating performance": "⛸️❄️✨",
        "healthy smoothie after workout": "🏋️‍♀️🥤💚",
    },
    "Law, Politics, and Justice": {
        "fighting for justice": "⚖️✊💼",
        "political election campaign": "🗳️💬🎉",
        "lawyer's legal defense": "👩‍⚖️⚖️📜",
        "peaceful protest movement": "✌️🚶‍♀️📣",
        "global political summit": "🌍🤝💼",
        "courtroom drama unfolding": "🏛️😮🎭",
        "international peace treaty": "✒️🌍☮️",
        "fighting corruption": "✊💼🔒",
        "youth in politics": "👦💼🗳️",
        "civic duty voting": "✅🗳️🏛️",
    },
    "Food, Drink, and Cuisine": {
        "fine dining experience": "🍽️🍷✨",
        "picnic in the park": "🧺🌳🌞",
        "sipping tea with a friend": "🫖👭❤️",
        "vegan lifestyle choice": "🌱🥗👌",
        "enjoying fast food": "🍔🍟😋",
        "coffee lovers' meeting": "☕💑🌆",
        "cooking family dinner": "👩‍🍳👨‍👧‍👦🍽️",
        "wine tasting event": "🍷🧐🥳",
        "baking holiday cookies": "🍪🎄👩‍🍳",
        "grilling summer BBQ": "🔥🍗🏖️",
        "food truck festival": "🚚🌮🎉",
        "romantic chocolate fondue": "🍫❤️🥂",
    },
    "Weather and Seasons": {
        "enjoying a sunny day": "🌞😎🏖️",
        "dancing in the rain": "💃🌧️☔",
        "snowman building fun": "☃️❄️😃",
        "autumn leaf peeping": "🍁👀🍂",
        "spring flower blossoming": "🌼🌱💚",
        "hot summer beach time": "🔥🏖️👙",
        "cold winter's night": "❄️🌙🧣",
        "thunderstorm fascination": "⛈️😲🌩️",
        "windy day adventure": "🌬️🧣🏃‍♂️",
        "sunset watching romance": "🌅💏❤️",
        "sunrise morning motivation": "🌞🌅💪",
        "cloud watching relaxation": "☁️👀",
    },
    "Triumph and Defeat": {
        "victory dance": "🏆💃😁",
        "crushed by failure": "😢❌👎",
        "battlefield triumph": "⚔️🏅🎉",
        "defeated in love": "💔😭👫",
        "champion's salute": "🥇🎖️👏",
    },
    "Love and Heartbreak": {
        "romantic moonlit kiss": "💏🌕❤️",
        "sobbing over breakup": "😭💔👋",
        "heart eyes for a crush": "😍❤️👀",
        "curse of unrequited love": "💘🚫😞",
        "surprise marriage proposal": "💍😲💑",
    },
    "Courage and Fear": {
        "brave face against odds": "😠💪🔥",
        "terror in a haunted house": "😱👻🏚️",
        "fearless warrior's charge": "🤺🏇🛡️",
        "paralyzed with fear": "😨❌🚶",
        "courage to speak out": "💪🎤✊",
    },
    "Joy and Despair": {
        "laughter with friends": "😂👫🎉",
        "desperate cry for help": "😢🆘🌧️",
        "celebrating personal success": "🎊🙌💯",
        "drowning in sorrow": "😭💧💔",
        "jumping for joy": "😃🎈🕺",
    },
    "Curiosity and Apathy": {
        "exploring new ideas": "🤔🔎🧠",
        "bored with the routine": "😑⏰🔄",
        "curious cat's discovery": "🐱🔍🎁",
        "unmoved by drama": "😒🎭❌",
        "excited for a mystery": "😲🕵️🧩",
    },
    "Harmony and Chaos": {
        "balanced mind meditation": "🧘‍♂️☯️🌿",
        "chaos in the city": "🏙️💥🚗",
        "harmony in nature": "🏞️🌼🦋",
        "riot and disorder": "😡✊🔥",
        "peaceful family dinner": "👨‍👩‍👧‍👦🍽️💕",
    },
    "Generosity and Greed": {
        "sharing a meal with homeless": "🍲❤️🏠",
        "greedy eyes on money": "😈💰👀",
        "generous heart donation": "❤️💵🏥",
        "hoarding wealth": "💰🏦😤",
        "gift of love": "🎁💝😘",
    },
    "Hope and Hopelessness": {
        "light of hope in darkness": "💡🌑✨",
        "lost in despair": "😔🌧️🗺️",
        "hopeful new beginning": "🌅🌱👍",
        "crying in isolation": "😢🏠🚪",
        "wishing on a star": "⭐🌠🙏",
    },
    "Friendship and Betrayal": {
        "friendship bracelet": "👫💖📿",
        "stabbed in the back": "😠🔪💔",
        "clowning around with friends": "🤡👬🎪",
        "betrayed by a partner": "😵👭❌",
        "loyal pet's love": "🐶❤️👩",
    },
    "Inspiration and Frustration": {
        "muse of creativity": "👼🎨🎵",
        "frustrated at writer's block": "😤✍️❌",
        "inspired by a mentor": "👩‍🏫💭✨",
        "angry at technology failure": "💻😡💥",
        "awed by nature's beauty": "🌺🏞️😍",
    },
    "Dreams and Nightmares": {
        "riding a unicorn to success": "🦄🌈💼",
        "chased by robotic clowns": "🤖🤡😱",
        "winning lottery in a dream": "💤💰🎉",
        "nightmare of public speaking": "😰🎙️👻",
        "dancing with a celebrity crush": "💃🕺😍",
    },
    "Extreme Culinary Emotions": {
        "falling in love with a sandwich": "❤️🥪😋",
        "hating pineapple on pizza": "🍍🍕😡",
        "food coma after a feast": "🍗🥘😴",
        "crying over spilled milkshake": "😢🥤💔",
        "screaming at a burnt cake": "🎂🔥😱",
    },
    "Absurd Workplace Situations": {
        "fighting with a photocopy machine": "👊🖨️😤",
        "flirting with a coffee machine": "😉☕💘",
        "elevator dance party": "🕺💃🏢",
        "boss turned into a cat": "👨‍💼🐱😲",
        "office chair race": "🪑🏁😂",
    },
    "Wild Romantic Encounters": {
        "kissing a frog prince": "💋🐸👑",
        "love triangle with a pizza": "❤️🍕🔼",
        "date with an imaginary friend": "👫💭🌹",
        "romance with a book character": "💖📚🧚",
        "breakup with a TV show": "💔📺😭",
    },
    "Bizarre Personal Achievements": {
        "world champion in thumb wrestling": "🏆👍🤼",
        "breaking the record for sneezing": "🎖️😤💨",
        "first person to swim in chocolate": "🥇🏊‍♀️🍫",
        "master of air guitar": "🎸💨🎶",
        "meditating on a rollercoaster": "🧘‍♂️🎢😯",
    },
    "Relationship Dynamics": {
        "first date butterflies": "🥰🦋🍽️",
        "long-distance love": "❤️✈️📱",
        "breakup blues": "💔😢🎶",
        "friendzone": "😊👫💔",
        "engagement excitement": "💍🎉😍",
    },
    "Work and Career": {
        "promotion party": "👔🎉💼",
        "burnout blues": "💻😓🔥",
        "job interview nerves": "🤝📝😰",
        "office romance": "💑💼✏️",
        "retirement relaxation": "👴🍹🏖️",
    },
    "Health and Wellness": {
        "yoga tranquility": "🧘‍♀️✌️😌",
        "junk food regret": "🍔🍟😫",
        "fitness goals": "🏃💪🎯",
        "mental health day": "💭🛀😊",
        "medical check-up anxiety": "🩺💉😧",
    },
    "Family and Friends": {
        "family game night": "👨‍👩‍👧🎲🎉",
        "best friends forever": "😊👯💖",
        "parenting joys and struggles": "👶😂😴",
        "pet love": "🐶🐱❤️",
        "sibling rivalry": "👦👧🥊",
    },
    "Education and Learning": {
        "exam stress": "📚💡😰",
        "graduation joy": "🎓🎉😀",
        "back-to-school excitement": "🎒🚌🏫",
        "love for reading": "📖❤️🤓",
        "teacher appreciation": "👩‍🏫🍎❤️",
    },
    "Travel and Exploration": {
        "road trip with friends": "🚗🗺️😎",
        "exotic vacation getaway": "🌴✈️🍹",
        "traveling solo adventure": "🧳🌏🚶",
        "mountain hiking thrill": "⛰️🥾🤩",
        "cultural exploration": "🕌🎎🎨",
        "camping under the stars": "🏕️🌌🔥",
        "business travel grind": "💼✈️😴",
        "cruise ship relaxation": "🚢🌊🌞",
        "backpacking on a budget": "🎒💲🌍",
        "staycation serenity": "🏠🛀😌",
    },
    "Sports and Leisure": {
        "victory celebration": "🏆💥🎉",
        "defeat despair": "😢🏁💔",
        "teamwork triumph": "🏀👫🏅",
        "fitness routine": "🏋️‍♂️🚴‍♀️🧘‍♀️",
        "golfing with friends": "🏌️‍♂️⛳🍻",
        "beach volleyball fun": "🏖️🏐😁",
        "fishing relaxation": "🎣🐟😊",
        "yoga peace": "🧘‍♀️🕉️☮️",
        "horseback riding joy": "🐎🏞️😍",
        "sailing adventure": "⛵🌊🌅",
    },
    "Creativity and Art": {
        "painting passion": "🎨❤️🖌️",
        "writing inspiration": "✍️💭📖",
        "musical jam session": "🎸🎤🎹",
        "dance expression": "💃🎶🕺",
        "photography exploration": "📸🏞️🏙️",
        "cooking masterpiece": "👩‍🍳🥘🎉",
        "sculpture creation": "🗿⚒️🌟",
        "fashion design": "👗✂️💄",
        "pottery tranquility": "🏺🤲😌",
        "filmmaking magic": "🎥🎬✨",
    },
    "Technology and Innovation": {
        "new gadget excitement": "📱⌚💥",
        "virtual reality immersion": "🕶️🎮🌐",
        "coding success": "💻🔍🎉",
        "tech startup hustle": "🚀💡💼",
        "social media connection": "📱💬❤️",
        "robotics fascination": "🤖🔧👀",
        "online shopping spree": "💳🛒💻",
        "e-learning growth": "💻📚🎓",
        "home automation comfort": "🏠🔌🛋️",
        "drone flying fun": "🚁🎮🌤️",
    },
    "Environment and Nature": {
        "gardening satisfaction": "🌻🌱👩‍🌾",
        "ocean conservation": "🌊🐬💙",
        "forest tranquility": "🌳🏞️🧘",
        "animal love": "🐶🐱🐰",
        "recycling responsibility": "♻️🗑️🌎",
        "sunset appreciation": "🌅👀❤️",
        "wildlife adventure": "🐘🦓🦒",
        "stargazing wonder": "🔭🌌💫",
        "urban green spaces": "🏙️🌳🚲",
        "rainy day coziness": "🌧️☔🛋️",
    },
    "Love and Romance": {
        "new love excitement": "💘🌹😍",
        "romantic proposal": "💍👩‍❤️‍💋‍👨🎉",
        "breakup heartache": "💔😢🌧️",
        "rekindling old flame": "🔥💏🕒",
        "long-term commitment": "❤️👫🏠",
        "secret crush": "😳💘🙊",
        "unrequited love": "😢💔👩‍❤️‍🚫",
        "passionate affair": "💋🔥🚪",
        "wedding bliss": "💒💏🎉",
        "platonic love": "💙👫👬",
    },
    "Anxiety and Stress": {
        "work-related stress": "💼📈😓",
        "social anxiety": "👫👀😰",
        "financial worries": "💰📉😟",
        "health anxiety": "🌡️💉😧",
        "academic pressure": "📚⏰😩",
        "relationship tension": "💏🥺💔",
        "parenting challenges": "👶🍼😵",
        "performance nerves": "🎤🎭😬",
        "fear of failure": "🎯💥😣",
        "daily overwhelm": "🗓️🏃😵",
    },
    "Joy and Celebration": {
        "birthday party": "🎂🎉😄",
        "achievement pride": "🏆🎖️😁",
        "new baby joy": "👶🎉🥰",
        "wedding day happiness": "💍👰😊",
        "holiday celebration": "🎄🎁🎊",
        "friendship appreciation": "👫❤️🎉",
        "retirement freedom": "👴🎉🏖️",
        "personal goal success": "🏁🥅😃",
        "new home excitement": "🏠🗝️🎉",
        "reunion delight": "👨‍👩‍👧‍👦🎈😆",
    },
    "Sadness and Grief": {
        "loss of a loved one": "😢💔👼",
        "breakup sorrow": "💔🚶😭",
        "job loss despair": "💼🚫😩",
        "illness struggle": "🤒💊😞",
        "friendship fallout": "👫💥😔",
        "pet loss": "🐶🐱💔",
        "missing home": "🏠❤️😢",
        "unfulfilled dreams": "🌈🚫😭",
        "loneliness": "🚶😢💔",
        "aging melancholy": "👴⌛😕",
    },
    "Curiosity and Discovery": {
        "learning a new hobby": "🎨🎻🤩",
        "exploring new cultures": "🌎🎎🕌",
        "scientific curiosity": "🔬🧪💡",
        "spiritual exploration": "🌌🧘‍♀️✨",
        "new relationship intrigue": "💑🔍❓",
        "career path discovery": "👩‍💼🛤️💼",
        "self-reflection": "🤔💭👤",
        "parenting wonder": "👶💫👨‍👩‍👧",
        "new technology interest": "📱💻🕹️",
        "artistic inspiration": "🎨🖌️🎭",
    },
}
raw2 = {
    "Health and Wellness": {
        "smoothie detox day": "🍏🥤🧘",
        "falling asleep after a long day": "😴🛌💤",
    },
    "Education and Learning": {
        "love for mathematics": "❤️🧮➗",
        "cracking the code in programming": "💻🔓🎉",
    },
    "Travel and Adventure": {
        "mountain hiking adventure": "🏔️🥾🧗",
        "exploring ancient ruins": "🏛️🔍🗺️",
    },
    "Family and Life Stages": {
        "first day of school nerves": "🎒🏫😰",
        "proud parenting moment": "👨‍👧❤️🏆",
    },
    "Business and Entrepreneurship": {
        "coffee-fueled work marathon": "☕💻🌙",
        "signing a big deal": "✍️💼💰",
    },
    "Science and Discovery": {
        "space telescope star gazing": "🔭🌌✨",
        "robotic innovation": "🤖💡🎓",
    },
    "Hobbies and Recreation": {
        "knitting a warm scarf": "🧶🧣😊",
        "joy of painting": "🎨🖼️😍",
    },
    "Culture and Society": {
        "pride parade celebration": "🏳️‍🌈🎉❤️",
        "community potluck dinner": "🏘️🍽️👨‍👩‍👦",
    },
    "Nature and Environment": {
        "recycling for Earth's wellbeing": "♻️🌍❤️",
        "mesmerized by a waterfall": "😍💧🏞️",
    },
    "Sexuality and Flirtation": {
        "romantic dinner date": "🕯️🍽️💏",
        "catching someone's eye": "👀❤️😘",
    },
    "Adventure and Exploration": {
        "diving with sharks": "🦈🌊🏊",
        "discovering a hidden cave": "🔦🕳️🗺️",
    },
    "Sports and Competitions": {
        "winning a gold medal": "🏅🏃💨",
        "intense chess match": "♟️🤔⏳",
    },
    "Art and Creativity": {
        "sculpting a masterpiece": "🗿🔨✨",
        "writing a bestseller": "✒️📖🏆",
    },
    "Friendship and Relationships": {
        "long-distance friendship": "👫🌍✉️",
        "breakup and recovery": "💔😢➡️😊",
    },
    "Work and Career": {
        "promotion celebration": "🎉💼🆙",
        "burning the midnight oil": "🕯️💻🌙",
    },
    "Food and Dining": {
        "experiencing exotic cuisine": "🍽️🌏😋",
        "cooking together with love": "👩‍🍳👨‍🍳❤️",
    },
    "Emotions and Feelings": {
        "overwhelmed with joy": "😭🎉😄",
        "deep in thought": "🤔💭🧠",
    },
    "Technology and Innovation": {
        "virtual reality gaming": "🎮🕶️🌐",
        "building a smart home": "🏠💡📲",
    },
}
for key, value in raw2.items():
    if key in raw:
        raw[key].update(value)
    else:
        raw[key] = value

love_sex_relationships_data = {
    "Love and Romance": {
        "candlelit dinner for two": "🕯️🍽️❤️",
        "falling in love": "😍❤️🏹",
        "anniversary celebration": "💏🎉🥂",
        "long-distance love": "❤️🌍✈️",
        "proposal and engagement": "💍👫💘",
        "stolen kiss": "💋🙈❤️",
        "dancing under the stars": "💃🕺🌌",
    },
    "Family and Relationships": {
        "family game night": "👨‍👩‍👧🎲😄",
        "growing old together": "👵❤️👴",
        "parenting joys and challenges": "👶🍼😅",
        "reunion with old friends": "👯‍♀️🎉🤗",
        "pet love": "🐶❤️😊",
        "connecting with siblings": "👭💕🤝",
    },
    "Dating and Flirtation": {
        "first date butterflies": "🥰🍴🦋",
        "flirting with a smile": "😉💬❤️",
        "online dating match": "💻❤️👫",
        "playing hard to get": "😏🏃💘",
        "sending love letters": "✉️❤️💌",
        "blind date excitement": "🙈🍽️❤️",
    },
    "Sexuality and Exploration": {
        "exploring desires": "🔍❤️🛏️",
        "spicing up the relationship": "🌶️❤️🔥",
        "safe sex awareness": "❤️🛌🎈",
        "expressing sexual orientation": "🏳️‍🌈❤️🌈",
        "romantic vacation": "❤️✈️🏩",
        "honeymoon phase": "💑🌙💞",
    },
    "Breakups and Healing": {
        "healing from a breakup": "💔😢💪",
        "letting go of the past": "👋🕒❤️",
        "support from friends": "💔👫🤗",
        "finding oneself again": "💔🧘❤️",
        "embracing single life": "💔😎🥳",
    },
    "Marriage and Commitment": {
        "wedding planning": "💑📋🎉",
        "saying 'I do'": "💑💍✨",
        "renewing vows": "💏💍🔄",
        "marriage ups and downs": "💑🎢❤️",
        "pregnancy announcement": "👶🎉💑",
    },
    "Friendship and Platonic Love": {
        "best friends forever": "👫💕∞",
        "supporting a friend": "👫🤗❤️",
        "friendship across cultures": "🌍👫🤗",
        "celebrating friendships": "👫🎉🍻",
    },
}

# You can add this to your existing data using the method shown earlier:
for key, value in love_sex_relationships_data.items():
    if key in raw:
        raw[key].update(value)
    else:
        raw[key] = value
skull_emoji_data = {
    "Extreme Activities and Risks": {
        "death-defying stunts": "💀🏍️🔥",
        "rock climbing without ropes": "💀🧗‍♂️🚫",
        "dangerous chemicals": "💀☠️🧪",
        "extreme snowboarding": "💀🏂❄️",
        "skydiving thrill": "💀✈️🪂",
    },
    "Health and Lifestyle": {
        "unhealthy junk food": "💀🍔🍟",
        "skull-crushing headache": "💀🤕😫",
        "dead tired": "💀😴",
        "death by caffeine": "💀☕🚫",
        "fatal allergies": "💀🥜⚠️",
    },
    "Culture and Entertainment": {
        "horror movie night": "💀🎬👻",
        "heavy metal concert": "💀🎸🤘",
        "reading dark poetry": "💀📖🌒",
        "gothic fashion": "💀👗🖤",
        "Halloween party": "💀🎃🎉",
    },
    "Emotions and Reactions": {
        "laughing to death": "💀😂",
        "bored to death": "💀😐",
        "scared to death": "💀😱",
        "dead serious": "💀😐✅",
        "killed by cuteness": "💀😍🐶",
    },
    "Technology and Social Media": {
        "dead phone battery": "💀📱",
        "dead link": "💀🔗",
        "dead computer": "💀💻",
        "dead-end code debugging": "💀🐛💻",
        "fatal system error": "💀💻🚨",
    },
    "Environment and Nature": {
        "deadly hurricane": "💀🌀",
        "poisonous plants": "💀🌿☠️",
        "fatal heatwave": "💀🌞🔥",
        "deadly snake": "💀🐍",
        "extinct species": "💀🦖🦕",
    },
    "Business and Work": {
        "dead-end job": "💀🏢",
        "deadlines approaching": "💀⏰",
        "death by meetings": "💀📅📈",
        "toxic work environment": "💀🏢☣️",
        "dead market": "💀💼📉",
    },
    "Relationships and Social": {
        "ghosting someone": "💀👻📱",
        "dead silence in conversation": "💀🗨️🚫",
        "toxic relationship": "💀❤️☣️",
        "breakup heartbreak": "💀💔",
        "end of friendship": "💀👫❌",
    },
}

# To merge with the existing data:
for key, value in skull_emoji_data.items():
    if key in raw:
        raw[key].update(value)
    else:
        raw[key] = value


concepts = [
    {"category": category, "concept": concept, "emoji": emoji}
    for category, concepts in raw.items()
    for concept, emoji in concepts.items()
]
